### ISSUE TITLE
Error: No diploid segments found, existing...

### ISSUE THREAD

**Issue by mjafin** [uci-cbcl/PyLOH#3]
Hi again,
I managed to run the pre-processing module for two cell line WGS samples (tumour/normal) fine with the latest updates to PyLOH. However, running the analysis itself I get the following error:
```
Error: No diploid segments found, existing...
```
Any ideas?

I took a look at the heatmap plots and they look pale in the middle compared to your example plots. Most of the red points are around (0,0) and some around (1,1). There are also several chromosomes where the tumour frequency seems to be 1 and normal frequency is somewhere between 0.3...0.7.

**Comment by yil8** [comment]
Hi,

I'm wondering if it Is OK for you to email me (yil8@uci.edu) the preprocessed PyLOH files of the cell line, namely *.PyLOH.counts *.PyLOH.segments and *.PyLOH.heatmap.plot ?

Since it is pale in the middle of the heatmap plot, I guess there aren't enough SNP sites within the data, or one allele of the tumor cell line is totally deleted.

Also just curious, since it is a tumor cell line, isn't it 100% tumor cells?

Thanks

**Comment by mjafin** [comment]
Thanks again, I'll send you the files today. The tumor sample should be pretty high purity but the normal was derived from plasma I believe.

**Comment by sweetie-mini** [comment]
Hi,
I got the same error, how did you solve it?
